import type { Package } from "@/types"

export const MOCK_PACKAGES: Package[] = [
  {
    id: "1",
    masterPackageId: "m1",
    title: "5D4N Japan Sakura Tour",
    shortDescription: "Witness the breathtaking cherry blossoms in Tokyo & Kyoto with guided tours and authentic dining.",
    description: "Experience the magic of Japan during peak cherry blossom season. Explore Tokyo's vibrant neighbourhoods, serene Kyoto temples, and iconic Mount Fuji.",
    category: "Cultural",
    destination: "Japan",
    region: "Asia",
    price: 4999,
    currency: "RM",
    durationDays: 5,
    featuredImageUrl: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&q=80",
    rating: 4.9,
    reviewCount: 128,
    isFeatured: true,
    isPopular: true,
    isCustomized: false,
    lastSyncedAt: new Date().toISOString(),
    highlightsJson: JSON.stringify(["Shibuya Crossing", "Fushimi Inari", "Mt. Fuji", "Arashiyama Bamboo"]),
    inclusionsJson: JSON.stringify(["Return flights", "4-star hotel", "Daily breakfast", "Licensed guide"]),
    exclusionsJson: JSON.stringify(["Personal shopping", "Optional tours", "Travel insurance"]),
    itineraryJson: JSON.stringify([
      { dayNumber: 1, title: "Arrival in Tokyo", description: "Check in and explore Shinjuku." },
      { dayNumber: 2, title: "Tokyo Highlights", description: "Shibuya, Harajuku, Akihabara." },
      { dayNumber: 3, title: "Day Trip to Mt. Fuji", description: "Fuji Five Lakes region." },
      { dayNumber: 4, title: "Kyoto", description: "Fushimi Inari, Arashiyama, Gion." },
      { dayNumber: 5, title: "Departure", description: "Transfer to Narita airport." },
    ]),
  },
  {
    id: "2",
    masterPackageId: "m2",
    title: "7D6N Bali Family Escape",
    shortDescription: "A perfect family retreat in the Island of Gods with temples, rice terraces and beach relaxation.",
    description: "Discover Bali's rich culture and stunning landscapes on this family-friendly package.",
    category: "Beach",
    destination: "Bali",
    region: "Southeast Asia",
    price: 3299,
    currency: "RM",
    durationDays: 7,
    featuredImageUrl: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=80",
    rating: 4.8,
    reviewCount: 96,
    isFeatured: true,
    isPopular: false,
    isCustomized: false,
    lastSyncedAt: new Date().toISOString(),
  },
  {
    id: "3",
    masterPackageId: "m3",
    title: "10D9N Europe Grand Tour",
    shortDescription: "Explore 5 iconic European cities — Paris, Amsterdam, Rome, Barcelona & Prague.",
    description: "A comprehensive tour covering the best of Western Europe with premium hotels and expert guides.",
    category: "City",
    destination: "Europe",
    region: "Europe",
    price: 8999,
    currency: "RM",
    durationDays: 10,
    featuredImageUrl: "https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=800&q=80",
    rating: 4.7,
    reviewCount: 74,
    isFeatured: false,
    isPopular: true,
    isCustomized: false,
    lastSyncedAt: new Date().toISOString(),
  },
  {
    id: "4",
    masterPackageId: "m4",
    title: "4D3N Maldives Overwater Retreat",
    shortDescription: "Stay in an overwater villa surrounded by crystal-clear turquoise waters and vibrant coral reefs.",
    description: "The ultimate luxury escape in the Maldives with snorkelling, sunset cruises and spa treatments.",
    category: "Beach",
    destination: "Maldives",
    region: "South Asia",
    price: 5599,
    currency: "RM",
    durationDays: 4,
    featuredImageUrl: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800&q=80",
    rating: 5.0,
    reviewCount: 42,
    isFeatured: true,
    isPopular: true,
    isCustomized: false,
    lastSyncedAt: new Date().toISOString(),
  },
  {
    id: "5",
    masterPackageId: "m5",
    title: "6D5N South Korea Discovery",
    shortDescription: "K-pop, palaces, street food and night markets — Seoul & Busan await you.",
    description: "Immerse yourself in South Korea's vibrant culture, from ancient palaces to modern K-culture.",
    category: "Cultural",
    destination: "South Korea",
    region: "Asia",
    price: 3799,
    currency: "RM",
    durationDays: 6,
    featuredImageUrl: "https://images.unsplash.com/photo-1517154421773-0529f29ea451?w=800&q=80",
    rating: 4.6,
    reviewCount: 55,
    isFeatured: false,
    isPopular: true,
    isCustomized: false,
    lastSyncedAt: new Date().toISOString(),
  },
  {
    id: "6",
    masterPackageId: "m6",
    title: "3D2N Cameron Highlands Retreat",
    shortDescription: "A cool highland escape with tea plantations, strawberry farms and nature walks.",
    description: "Escape the city heat with a relaxing trip to Malaysia's most popular highland destination.",
    category: "Nature",
    destination: "Cameron Highlands",
    region: "Malaysia",
    price: 699,
    currency: "RM",
    durationDays: 3,
    featuredImageUrl: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80",
    rating: 4.4,
    reviewCount: 110,
    isFeatured: false,
    isPopular: false,
    isCustomized: false,
    lastSyncedAt: new Date().toISOString(),
  },
]

export const CATEGORIES = ["All", "Beach", "Cultural", "City", "Nature", "Adventure"]
export const DESTINATIONS = ["All", "Japan", "Bali", "Europe", "Maldives", "South Korea", "Malaysia"]
